### PR TITLE
Updated to ZIO version 1.0.0-RC19-2

### PR DESCRIPTION
**Pull request by randomf**

### CODE REVIEW

**Comment by mlangc** [comment]
Thanks a lot for your contribution! Shouldn't we go straight to `1.0.0-RC19-2`, or do you want a release specifically for `1.0.0-RC19-1`?

**Comment by mlangc** [comment]
I've [just read](https://github.com/zio/zio/releases/tag/v1.0.0-RC19-2) that `1.0.0-RC19-2` is meant to be binary compatible with `1.0.0-RC19-1`, so in theory it should not matter, but I think that depending on `1.0.0-RC19-2` might still be preferable.

**Comment by randomf** [comment]
Of course let’s do `1.0.0-RC19-2`. I haven’t spotted the new release

**Comment by mlangc** [comment]
Thanks a lot for submitting the first pull request for slf4zio!



 I'm going to release to maven central right away.

**Pull request merged**
